domain_path: /home/jkelley/Documents/Xilinx/zedboard_eth_test0/software/platform/zynq_fsbl/zynq_fsbl_bsp
app_src_dir: /opt/Xilinx/2025.2/Vitis/data/embeddedsw/lib/sw_apps/zynq_fsbl
template: zynq_fsbl
lang: c
