# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_resetSystemStats
    rt::HARTNDb_startSystemStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "./.Xil/Vivado-536186-jkelleylaptop/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    rt::set_parameter datapathDensePacking false
    set rt::partid xc7z020clg484-1
    source $::env(HRT_TCL_PATH)/rtSynthParallelPrep.tcl
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common.tcl 
    set rt::defaultWorkLibName xil_defaultlib
    rt::set_parameter defaultVhdlWorkLib xil_defaultlib

    rt::set_parameter loadVhdl2008Libs false
    rt::set_parameter loadVhdl2019Libs false
    rt::set_parameter deferParseUntilElab true
    rt::set_parameter sortHdlCommandLine true
    rt::set_parameter singleFileBasedDefaultNettype false
    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv -include {
    /home/jkelley/Documents/Xilinx/zedboard_eth_test0/hardware/zedboard_eth_test0.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog
    /home/jkelley/Documents/Xilinx/zedboard_eth_test0/hardware/zedboard_eth_test0.gen/sources_1/bd/design_1/ipshared/00fe/hdl/verilog
    /opt/Xilinx/2025.2/data/rsb/busdef
  } {
      /opt/Xilinx/2025.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv
      /opt/Xilinx/2025.2/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv
      /opt/Xilinx/2025.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv
      /home/jkelley/Documents/Xilinx/zedboard_eth_test0/hardware/zedboard_eth_test0.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/sc_util_v1_0_vl_rfs.sv
      /home/jkelley/Documents/Xilinx/zedboard_eth_test0/hardware/zedboard_eth_test0.gen/sources_1/bd/design_1/ipshared/0848/hdl/sc_switchboard_v1_0_vl_rfs.sv
      /home/jkelley/Documents/Xilinx/zedboard_eth_test0/hardware/zedboard_eth_test0.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_2/synth/bd_afc3_arinsw_0.sv
      /home/jkelley/Documents/Xilinx/zedboard_eth_test0/hardware/zedboard_eth_test0.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_3/synth/bd_afc3_rinsw_0.sv
      /home/jkelley/Documents/Xilinx/zedboard_eth_test0/hardware/zedboard_eth_test0.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_4/synth/bd_afc3_awinsw_0.sv
      /home/jkelley/Documents/Xilinx/zedboard_eth_test0/hardware/zedboard_eth_test0.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_5/synth/bd_afc3_winsw_0.sv
      /home/jkelley/Documents/Xilinx/zedboard_eth_test0/hardware/zedboard_eth_test0.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_6/synth/bd_afc3_binsw_0.sv
      /home/jkelley/Documents/Xilinx/zedboard_eth_test0/hardware/zedboard_eth_test0.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_7/synth/bd_afc3_aroutsw_0.sv
      /home/jkelley/Documents/Xilinx/zedboard_eth_test0/hardware/zedboard_eth_test0.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_8/synth/bd_afc3_routsw_0.sv
      /home/jkelley/Documents/Xilinx/zedboard_eth_test0/hardware/zedboard_eth_test0.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_9/synth/bd_afc3_awoutsw_0.sv
      /home/jkelley/Documents/Xilinx/zedboard_eth_test0/hardware/zedboard_eth_test0.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_10/synth/bd_afc3_woutsw_0.sv
      /home/jkelley/Documents/Xilinx/zedboard_eth_test0/hardware/zedboard_eth_test0.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_11/synth/bd_afc3_boutsw_0.sv
      /home/jkelley/Documents/Xilinx/zedboard_eth_test0/hardware/zedboard_eth_test0.gen/sources_1/bd/design_1/ipshared/00fe/hdl/sc_node_v1_0_vl_rfs.sv
      /home/jkelley/Documents/Xilinx/zedboard_eth_test0/hardware/zedboard_eth_test0.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_12/synth/bd_afc3_arni_0.sv
      /home/jkelley/Documents/Xilinx/zedboard_eth_test0/hardware/zedboard_eth_test0.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_13/synth/bd_afc3_rni_0.sv
      /home/jkelley/Documents/Xilinx/zedboard_eth_test0/hardware/zedboard_eth_test0.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_14/synth/bd_afc3_awni_0.sv
      /home/jkelley/Documents/Xilinx/zedboard_eth_test0/hardware/zedboard_eth_test0.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_15/synth/bd_afc3_wni_0.sv
      /home/jkelley/Documents/Xilinx/zedboard_eth_test0/hardware/zedboard_eth_test0.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_16/synth/bd_afc3_bni_0.sv
      /home/jkelley/Documents/Xilinx/zedboard_eth_test0/hardware/zedboard_eth_test0.gen/sources_1/bd/design_1/ipshared/3d9a/hdl/sc_mmu_v1_0_vl_rfs.sv
      /home/jkelley/Documents/Xilinx/zedboard_eth_test0/hardware/zedboard_eth_test0.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_17/synth/bd_afc3_s00mmu_0.sv
      /home/jkelley/Documents/Xilinx/zedboard_eth_test0/hardware/zedboard_eth_test0.gen/sources_1/bd/design_1/ipshared/7785/hdl/sc_transaction_regulator_v1_0_vl_rfs.sv
      /home/jkelley/Documents/Xilinx/zedboard_eth_test0/hardware/zedboard_eth_test0.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_18/synth/bd_afc3_s00tr_0.sv
      /home/jkelley/Documents/Xilinx/zedboard_eth_test0/hardware/zedboard_eth_test0.gen/sources_1/bd/design_1/ipshared/3051/hdl/sc_si_converter_v1_0_vl_rfs.sv
      /home/jkelley/Documents/Xilinx/zedboard_eth_test0/hardware/zedboard_eth_test0.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_19/synth/bd_afc3_s00sic_0.sv
      /home/jkelley/Documents/Xilinx/zedboard_eth_test0/hardware/zedboard_eth_test0.gen/sources_1/bd/design_1/ipshared/852f/hdl/sc_axi2sc_v1_0_vl_rfs.sv
      /home/jkelley/Documents/Xilinx/zedboard_eth_test0/hardware/zedboard_eth_test0.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_20/synth/bd_afc3_s00a2s_0.sv
      /home/jkelley/Documents/Xilinx/zedboard_eth_test0/hardware/zedboard_eth_test0.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_21/synth/bd_afc3_sarn_0.sv
      /home/jkelley/Documents/Xilinx/zedboard_eth_test0/hardware/zedboard_eth_test0.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_22/synth/bd_afc3_srn_0.sv
      /home/jkelley/Documents/Xilinx/zedboard_eth_test0/hardware/zedboard_eth_test0.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_23/synth/bd_afc3_sawn_0.sv
      /home/jkelley/Documents/Xilinx/zedboard_eth_test0/hardware/zedboard_eth_test0.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_24/synth/bd_afc3_swn_0.sv
      /home/jkelley/Documents/Xilinx/zedboard_eth_test0/hardware/zedboard_eth_test0.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_25/synth/bd_afc3_sbn_0.sv
      /home/jkelley/Documents/Xilinx/zedboard_eth_test0/hardware/zedboard_eth_test0.gen/sources_1/bd/design_1/ipshared/fca9/hdl/sc_sc2axi_v1_0_vl_rfs.sv
      /home/jkelley/Documents/Xilinx/zedboard_eth_test0/hardware/zedboard_eth_test0.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_26/synth/bd_afc3_m00s2a_0.sv
      /home/jkelley/Documents/Xilinx/zedboard_eth_test0/hardware/zedboard_eth_test0.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_27/synth/bd_afc3_m00arn_0.sv
      /home/jkelley/Documents/Xilinx/zedboard_eth_test0/hardware/zedboard_eth_test0.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_28/synth/bd_afc3_m00rn_0.sv
      /home/jkelley/Documents/Xilinx/zedboard_eth_test0/hardware/zedboard_eth_test0.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_29/synth/bd_afc3_m00awn_0.sv
      /home/jkelley/Documents/Xilinx/zedboard_eth_test0/hardware/zedboard_eth_test0.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_30/synth/bd_afc3_m00wn_0.sv
      /home/jkelley/Documents/Xilinx/zedboard_eth_test0/hardware/zedboard_eth_test0.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_31/synth/bd_afc3_m00bn_0.sv
      /home/jkelley/Documents/Xilinx/zedboard_eth_test0/hardware/zedboard_eth_test0.gen/sources_1/bd/design_1/ipshared/e44a/hdl/sc_exit_v1_0_vl_rfs.sv
      /home/jkelley/Documents/Xilinx/zedboard_eth_test0/hardware/zedboard_eth_test0.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_32/synth/bd_afc3_m00e_0.sv
      /home/jkelley/Documents/Xilinx/zedboard_eth_test0/hardware/zedboard_eth_test0.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_33/synth/bd_afc3_m01s2a_0.sv
      /home/jkelley/Documents/Xilinx/zedboard_eth_test0/hardware/zedboard_eth_test0.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_34/synth/bd_afc3_m01arn_0.sv
      /home/jkelley/Documents/Xilinx/zedboard_eth_test0/hardware/zedboard_eth_test0.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_35/synth/bd_afc3_m01rn_0.sv
      /home/jkelley/Documents/Xilinx/zedboard_eth_test0/hardware/zedboard_eth_test0.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_36/synth/bd_afc3_m01awn_0.sv
      /home/jkelley/Documents/Xilinx/zedboard_eth_test0/hardware/zedboard_eth_test0.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_37/synth/bd_afc3_m01wn_0.sv
      /home/jkelley/Documents/Xilinx/zedboard_eth_test0/hardware/zedboard_eth_test0.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_38/synth/bd_afc3_m01bn_0.sv
      /home/jkelley/Documents/Xilinx/zedboard_eth_test0/hardware/zedboard_eth_test0.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_39/synth/bd_afc3_m01e_0.sv
    }
      rt::read_verilog -include {
    /home/jkelley/Documents/Xilinx/zedboard_eth_test0/hardware/zedboard_eth_test0.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog
    /home/jkelley/Documents/Xilinx/zedboard_eth_test0/hardware/zedboard_eth_test0.gen/sources_1/bd/design_1/ipshared/00fe/hdl/verilog
    /opt/Xilinx/2025.2/data/rsb/busdef
  } {
      /home/jkelley/Documents/Xilinx/zedboard_eth_test0/hardware/zedboard_eth_test0.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/synth/bd_afc3.v
      /home/jkelley/Documents/Xilinx/zedboard_eth_test0/hardware/zedboard_eth_test0.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/synth/design_1_axi_smc_0.v
    }
      rt::read_vhdl -lib xpm /opt/Xilinx/2025.2/data/ip/xpm/xpm_VCOMP.vhd
      rt::read_vhdl -lib proc_sys_reset_v5_0_17 /home/jkelley/Documents/Xilinx/zedboard_eth_test0/hardware/zedboard_eth_test0.gen/sources_1/bd/design_1/ipshared/9438/hdl/proc_sys_reset_v5_0_vh_rfs.vhd
      rt::read_vhdl -lib xil_defaultlib /home/jkelley/Documents/Xilinx/zedboard_eth_test0/hardware/zedboard_eth_test0.gen/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_1/synth/bd_afc3_psr_aclk_0.vhd
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top design_1_axi_smc_0
    rt::set_parameter enableIncremental true
    rt::set_parameter markDebugPreservationLevel "enable"
    set rt::reportTiming false
    rt::set_parameter elaborateOnly true
    rt::set_parameter elaborateRtl true
    rt::set_parameter eliminateRedundantBitOperator false
    rt::set_parameter dataflowBusHighlighting false
    rt::set_parameter generateDataflowBusNetlist false
    rt::set_parameter dataFlowViewInElab false
    rt::set_parameter busViewFixBrokenConnections false
    rt::set_parameter elaborateRtlOnlyFlow false
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter merge_flipflops true
    rt::set_parameter srlDepthThreshold 3
    rt::set_parameter rstSrlDepthThreshold 4
# MODE: 
    rt::set_parameter webTalkPath {}
    rt::set_parameter synthDebugLog false
    rt::set_parameter printModuleName false
    rt::set_parameter enableSplitFlowPath "./.Xil/Vivado-536186-jkelleylaptop/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_rtlelab -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    if { $rt::flowresult == 1 } { return -code error }


    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
uplevel #0 { 
   if {[info exists rt::doParallel] && $rt::doParallel} {
     rt::async_wait "asyncParallelOpen"
     rt::parallel_close
   }
   $rt::db resetHdlParse
   set hsKey [rt::get_parameter helper_shm_key] 
   if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
      $rt::db killSynthHelper $hsKey
   } 
   source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  }
 return -code "error" $rt::result
}
